blank_issues_enabled: false
contact_links:
  - name: ‚ùì Question
    url: https://github.com/panva/hpke/discussions/new?category=q-a
    about: Have a question about using @panva/hpke? Head over to the discussions "Q&A" Category
  - name: üí° Feature proposal
    url: https://github.com/panva/hpke/discussions/new?category=ideas
    about: Have a proposal for a new feature? Head over to the discussions "Ideas" Category
  - name: Support the project
    url: https://github.com/sponsors/panva
    about:
      Are you asking your nth question? Relying on @panva/hpke for critical operations? Consider
      supporting the project so that it may continue being maintained.
